# Generated by Django 4.0.1 on 2022-01-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('externalId', models.CharField(default='0', max_length=40, primary_key=True, serialize=False)),
                ('areaSqm', models.IntegerField(default=0)),
                ('isRoomActive', models.BooleanField(default=False)),
                ('roomMates', models.CharField(default='0', max_length=5)),
                ('rent', models.IntegerField(default=0)),
                ('deposit', models.IntegerField(default=0)),
                ('additionalCost', models.IntegerField(default=0)),
                ('registrationCost', models.IntegerField(default=0)),
                ('city', models.CharField(default='Nowhere', max_length=40)),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('postalCode', models.CharField(default='-1', max_length=40)),
                ('costPerSqm', models.IntegerField(default=0)),
            ],
        ),
    ]
