# Generated by Django 4.0.1 on 2022-01-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='externalId',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
