# Generated by Django 4.0.1 on 2022-01-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_property_externalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='costPerSqm',
        ),
    ]
