# Generated by Django 4.0.1 on 2022-01-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_property_costpersqm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='costPerSqm',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
